baseURL                = "https://pages.splazma.site/"
title                  = "Splazma Pages"
enableRobotsTXT        = true
enableGitInfo          = true
defaultContentLanguage = "en"
enableInlineShortcodes = true
languageCode           = 'en-us'
pluralizeListTitles    = false
disablePathToLower     = true

[outputs]
home    = ["HTML"]
page    = ["HTML"]
section = ["HTML", "RSS"]

[module.imports]
path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.renderHooks.link]
useEmbedded = "fallback"

[markup.highlight]
noClasses = false

[[menu.main]]
identifier = "version"
name       = "Latest git"
url        = "https://pages.splazma.site/version-selector/"
weight     = 1

[[menu.main.params]]
type     = "version"
outdated = false  # set for any version that isn't the current one
version  = ""     # only change when setting the version, otherwise it is "Latest git" by default

[[menu.main]]
identifier = "Home"
name       = "Home"
url        = "https://splazma.site/"
weight     = 2

[[menu.main]]
name   = "Search"
weight = 5
[menu.main.params]
type = "search"

[[menu.main]]
name   = "Telegram"
weight = 7
url    = "https://t.me/sfirebase"
[menu.main.params]
icon = "telegram"

[params]
description        = "Splazma Pages documentation."
displayUpdatedDate = true
dateFormat         = "January 2, 2006"

[params.navbar]
displayTitle = true
displayLogo  = true
width        = "full"

[params.navbar.logo]
path = "favicon.svg"
dark = "favicon-dark.svg"
height = 30
width = 30

[params.page]
width = "full"

[params.theme]
default       = "dark"
displayToggle = true

[params.footer]
enable           = false
displayCopyright = true
displayPoweredBy = true
width            = "normal"

[params.search]
enable = true
type   = "flexsearch"

[params.search.flexsearch]
index = "content"

[params.editURL]
enable = true
base   = "https://github.com/DillerOFire/splazma-pages/edit/main/content/"

[params.blog.list]
displayTags = true

[params.comments]
enable = false
